# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tom/workspace_cpp/garmintools-0.10

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tom/workspace_cpp/garmintools-0.10

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom/workspace_cpp/garmintools-0.10/CMakeFiles /home/tom/workspace_cpp/garmintools-0.10/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom/workspace_cpp/garmintools-0.10/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mytest

# Build rule for target.
mytest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mytest
.PHONY : mytest

# fast build rule for target.
mytest/fast:
	$(MAKE) -f CMakeFiles/mytest.dir/build.make CMakeFiles/mytest.dir/build
.PHONY : mytest/fast

#=============================================================================
# Target rules for targets named usb_comm

# Build rule for target.
usb_comm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 usb_comm
.PHONY : usb_comm

# fast build rule for target.
usb_comm/fast:
	$(MAKE) -f CMakeFiles/usb_comm.dir/build.make CMakeFiles/usb_comm.dir/build
.PHONY : usb_comm/fast

src/tst.o: src/tst.cpp.o
.PHONY : src/tst.o

# target to build an object file
src/tst.cpp.o:
	$(MAKE) -f CMakeFiles/mytest.dir/build.make CMakeFiles/mytest.dir/src/tst.cpp.o
.PHONY : src/tst.cpp.o

src/tst.i: src/tst.cpp.i
.PHONY : src/tst.i

# target to preprocess a source file
src/tst.cpp.i:
	$(MAKE) -f CMakeFiles/mytest.dir/build.make CMakeFiles/mytest.dir/src/tst.cpp.i
.PHONY : src/tst.cpp.i

src/tst.s: src/tst.cpp.s
.PHONY : src/tst.s

# target to generate assembly for a file
src/tst.cpp.s:
	$(MAKE) -f CMakeFiles/mytest.dir/build.make CMakeFiles/mytest.dir/src/tst.cpp.s
.PHONY : src/tst.cpp.s

src/usb_comm.o: src/usb_comm.c.o
.PHONY : src/usb_comm.o

# target to build an object file
src/usb_comm.c.o:
	$(MAKE) -f CMakeFiles/usb_comm.dir/build.make CMakeFiles/usb_comm.dir/src/usb_comm.c.o
.PHONY : src/usb_comm.c.o

src/usb_comm.i: src/usb_comm.c.i
.PHONY : src/usb_comm.i

# target to preprocess a source file
src/usb_comm.c.i:
	$(MAKE) -f CMakeFiles/usb_comm.dir/build.make CMakeFiles/usb_comm.dir/src/usb_comm.c.i
.PHONY : src/usb_comm.c.i

src/usb_comm.s: src/usb_comm.c.s
.PHONY : src/usb_comm.s

# target to generate assembly for a file
src/usb_comm.c.s:
	$(MAKE) -f CMakeFiles/usb_comm.dir/build.make CMakeFiles/usb_comm.dir/src/usb_comm.c.s
.PHONY : src/usb_comm.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mytest"
	@echo "... rebuild_cache"
	@echo "... usb_comm"
	@echo "... src/tst.o"
	@echo "... src/tst.i"
	@echo "... src/tst.s"
	@echo "... src/usb_comm.o"
	@echo "... src/usb_comm.i"
	@echo "... src/usb_comm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

